services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=tfa
      - POSTGRES_PASSWORD=tfa#123
      - POSTGRES_DB=tfa

volumes:
  postgres_data: