from graphene import Enum


class AnimeSortByEnum(Enum):
    TIME_TO_WATCH_ASC = "TIME_TO_WATCH_ASC"
    TIME_TO_WATCH_DESC = "TIME_TO_WATCH_DESC"
    NUM_EPISODES_ASC = "NUM_EPISODES_ASC"
    NUM_EPISODES_DESC = "NUM_EPISODES_DESC"
    TITLE_ASC = "TITLE_ASC"
    TITLE_DESC = "TITLE_DESC"
    AVERAGE_EP_DURATION_ASC = "AVERAGE_EP_DURATION_ASC"
    AVERAGE_EP_DURATION_DESC = "AVERAGE_EP_DURATION_DESC"
